name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
    paths:
      - 'Dockerfile'  # Trigger when the Dockerfile changes
      - '**/*.py'     # Trigger when Python files change
      - '.github/workflows/github_actions.yml'  # Trigger when this workflow changes

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build and push Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/house_price_prediction:latest
