apiVersion: v1
kind: Service
metadata:
  name: house-price-pred-service
  labels:
    app: house-price-pred
spec:
  type: LoadBalancer # Use "NodePort" or "ClusterIP" if LoadBalancer is not required
  ports:
  - port: 80         # Port exposed to the outside
    targetPort: 8000 # Port on the container
    protocol: TCP
  selector:
    app: house-price-pred
